### ISSUE TITLE
Implementar o banco de dados ao bot

### ISSUE THREAD

**Issue by PauloGoncalvesLima** [ChatBot-Bino/Chatbot-Bino#39]
Implementação de um banco de dados, usando o mongodb, que seja capaz de armazenar os dados do usuário.

**Comment by pedro-cella** [comment]
![Screenshot from 2019-10-25 10-57-48](https://user-images.githubusercontent.com/49076513/67577201-6a85b700-f716-11e9-9bd1-73004c1933e0.png)

<p> Erro na parte de estabelecer a conexão com o banco de dados.</p>
