### ISSUE TITLE
Consertar o custon action server

### ISSUE THREAD

**Issue by PauloGoncalvesLima** [ChatBot-Bino/Chatbot-Bino#55]
o custon action server não roda junto quando se tenta testar o bot no modo de shell/console.
mesmo seguindo o tutorial disponivel no site do rasa.
https://rasa.com/docs/rasa/user-guide/running-rasa-with-docker/

![Screenshot from 2019-10-12 15-30-40](https://user-images.githubusercontent.com/18203100/66706098-4fbe4600-ed05-11e9-8349-5a738cd684a6.png)

- [x] Testar o rasa shell e ver se a custon action funciona.

**Comment by pedro-cella** [comment]
Update novo error, mal funcionamento da custom action com o bot online no telegram
![Screenshot from 2019-10-22 19-37-31](https://user-images.githubusercontent.com/49076513/67340375-9da42c80-f503-11e9-8d9a-105710106dc4.png)

- [ ] Custom actions no bot online
