### ISSUE TITLE
Criar os stories e intents para a funcionalidade de Gerenciamento de Faltas

### ISSUE THREAD

**Issue by pedro-cella** [ChatBot-Bino/Chatbot-Bino#61]
Criação dos stories e intents voltados para a criação de respostas do bot voltadas para a funcionalidade de gerenciamento de faltas.

**Comment by irwinschmitt** [comment]
Issue fechada para melhor organização. Issues mais específicas foram criadas.

https://github.com/ChatBot-Bino/Chatbot-Bino/issues/85
https://github.com/ChatBot-Bino/Chatbot-Bino/issues/86
https://github.com/ChatBot-Bino/Chatbot-Bino/issues/87
