### ISSUE TITLE
Pesquisar sobre servidor, e achar alternativas de se conectar.

### ISSUE THREAD

**Issue by pedro-cella** [ChatBot-Bino/Chatbot-Bino#70]
<p>Pesquisar sobre servidores</p>

- [x] Como se conectar a um servidor
- [x] Locais para se estabelecer um servidor
- [x] Custo para se ter um servidor

**Comment by irwinschmitt** [comment]
[Where to host Telegram Bots - GitHub](https://github.com/python-telegram-bot/python-telegram-bot/wiki/Where-to-host-Telegram-Bots)

**Comment by pedro-cella** [comment]
O Guilherme Lacerda do Lappis sugeriu alugar uma maquina virtual dentro do Digital Ocean, o abrir a conta é dado 100 dólares para usar em 2 meses.

https://www.digitalocean.com/pricing/

**Comment by PauloGoncalvesLima** [comment]
Fechando a issue pois a pesquisa foi feita.
