### ISSUE TITLE
Criar uma custom action voltada para a funcionalidade de faltas

### ISSUE THREAD

**Issue by pedro-cella** [ChatBot-Bino/Chatbot-Bino#79]
Tem-se que criar uma custom action, voltada para a guardar a quantidade de faltas do usuário:
- [ ] Recebe a quantidade de matérias a serem cadastradas
- [ ] Contabiliza as faltas
- [ ]  Mostra qual matéria e a quantidade de faltas
- [ ] Faltando pouco para o limite maximo de faltas o bot manda um aviso

**Comment by PauloGoncalvesLima** [comment]
Fechando a issue pois o irwin tomou essa frente do projeto.
