### ISSUE TITLE
Organizar diretórios do repositório

### ISSUE THREAD

**Issue by irwinschmitt** [ChatBot-Bino/Chatbot-Bino#82]
### Descrição
O rasa está na pasta *bot* do repositório. O nome é genérico e é necessário uma melhor divisão para representar as tarefas realizadas.

### Sugestão
Uma forma simples de resolver é alterando o nome do diretório *bot* para *rasa*, representando melhor o conteúdo. Assim, poderão ter outras pastas fora de *rasa* que ainda sejam partes do bot.

├── ~bot~ rasa
│   ├── actions
│   └── data
├── cronjobs
├── docker
│   ├── .Dockerfile
├── docks
└── [...]

**Comment by PauloGoncalvesLima** [comment]
Vou fechar a issue pois creio eu que resolvemos ela no grupo do Telegram.
