### ISSUE TITLE
Custom action de gerenciar atividades não esta funcionando

### ISSUE THREAD

**Issue by pedro-cella** [ChatBot-Bino/Chatbot-Bino#94]
![Screenshot from 2019-11-19 20-59-18](https://user-images.githubusercontent.com/49076513/69197232-a0e50500-0b0f-11ea-95c8-95e8a9f62674.png)

**Comment by irwinschmitt** [comment]
Envie o log completo, por favor

**Comment by PauloGoncalvesLima** [comment]
Não é esse erro. Nenhuma das coisas citadas tem conexão com o erro.
O erro foi causado pelo fato do docker das custon actions não está rodando.
Que no caso eu ja sei porque mas ainda não consegui consertar.

**Comment by irwinschmitt** [comment]
O bot estava rodando no Telegram?

**Comment by irwinschmitt** [comment]
https://github.com/RasaHQ/rasa/issues/2857

**Comment by irwinschmitt** [comment]
Quando terminar o gerenciador de faltas resolvo isso

**Comment by PauloGoncalvesLima** [comment]
rodou hj de tarde.
mas esse erro deu agora de noite. E vou tentar resolver ele amanha.

**Comment by irwinschmitt** [comment]
> rodou hj de tarde.
> mas esse erro deu agora de noite. E vou tentar resolver ele amanha.

Tentou executar uma custom action durante a tarde? Só estava dando problema nas custom actions, stories sem elas estavam rodando corretamente quando testei.

**Comment by PauloGoncalvesLima** [comment]
Sim rodei as custon actions no telegram e no shell ambas estavam funcionando. E as stories não precisam do docker das custon actions então faz sentido o fato delas rodarem sem as custon actions

**Comment by irwinschmitt** [comment]
E aí, qual foi a resolução?
